---
- name: Set up web server
  hosts: web
  become: true
  vars:
    ansible_user: "{{ deploy_user }}"
  roles:
    - letsencrypt
    - nginx

- name: Set up CONSUL DEMOCRACY
  hosts: web
  become: true
  become_user: "{{ deploy_user }}"
  vars:
    # https://github.com/ansible/proposals/issues/89
    ansible_user: "{{ deploy_user }}"
  roles:
    - folder_structure
    - ruby
    - nodejs
    - rails
    - rails_zatsit
    - queue
    - puma

- name: Post-installation tasks
  hosts: web
  become: true
  vars:
    ansible_user: "{{ deploy_user }}"
  roles:
    - memcached
    - timezone

- name: Install Errbit
  hosts: web
  become: true
  vars:
    ansible_user: "{{ deploy_user }}"
  roles:
    - role: mongodb
      when: errbit|bool
    - role: errbit
      become_user: "{{ deploy_user }}"
      when: errbit|bool

- name: Install Google Ops Agent
  hosts: web
  become: true
  roles:
    - google_ops-agent

# - name: Check system
#   hosts: web
#   become: true
#   vars:
#     ansible_user: "{{ deploy_user }}"
#   roles:
#     - specs
