---
- name: Get secret zatsit-democracy-{{ env_shortname }}-db-user
  gcp_vault_secret:
    name: "zatsit-democracy-{{ env_shortname }}-db-user"
  register: r_secret_db_user

- name: Get secret zatsit-democracy-{{ env_shortname }}-db-password
  gcp_vault_secret:
    name: "zatsit-democracy-{{ env_shortname }}-db-password"
  register: r_secret_db_password
