---
- name: Get user UID
  shell: "id -u"
  register: current_uid

- name: Restart Puma
  systemd:
    name: "{{ puma_service_unit_name }}.service"
    daemon_reload: true
    enabled: true
    state: restarted
    scope: user
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ current_uid.stdout }}"
