---
- name: Precompile assets
  shell: "{{ fnm_command }} && {{ rvm_command }} && fnm exec bin/rake assets:precompile RAILS_ENV={{ env }}"
  args:
    chdir: "{{ release_dir }}"
    executable: /bin/bash

- name: Get user UID
  shell: "id -u"
  register: current_uid

- name: Restart Puma
  systemd:
    name: "{{ puma_service_unit_name }}.service"
    daemon_reload: true
    enabled: true
    state: restarted
    scope: user
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ current_uid.stdout }}"
