---
- name: Get secret zatsit-democracy-{{ env }}-db-user
  gcp_vault_secret:
    name: "zatsit-democracy-{{ env }}-db-user"
  register: r_secret_db_user

- name: Get secret zatsit-democracy-{{ env }}-db-password
  gcp_vault_secret:
    name: "zatsit-democracy-{{ env }}-db-password"
  register: r_secret_db_password

- name: Get secret zatsit-democracy-{{ env }}-gmail-app-usermail
  gcp_vault_secret:
    name: "zatsit-democracy-{{ env }}-gmail-app-usermail"
  register: r_secret_gmail_app_usermail

- name: Get secret zatsit-democracy-{{ env }}-gmail-app-password
  gcp_vault_secret:
    name: "zatsit-democracy-{{ env }}-gmail-app-password"
  register: r_secret_gmail_app_password

- name: Get secret zatsit-democracy-{{ env }}-oauth2-client-id
  gcp_vault_secret:
    name: "zatsit-democracy-{{ env }}-oauth2-client-id"
  register: r_secret_oauth2_client_id

- name: Get secret zatsit-democracy-{{ env }}-oauth2-client-secret
  gcp_vault_secret:
    name: "zatsit-democracy-{{ env }}-oauth2-client-secret"
  register: r_secret_oauth2_client_secret
