---
- name: Get secret zats-democracy-db-user
  gcp_vault_secret:
    name: "zats-democracy-db-user"
  register: r_secret_db_user

- name: Get secret zats-democracy-db-password
  gcp_vault_secret:
    name: "zats-democracy-db-password"
  register: r_secret_db_password

- name: Get secret zats-democracy-gmail-app-usermail
  gcp_vault_secret:
    name: "zats-democracy-gmail-app-usermail"
  register: r_secret_gmail_app_usermail

- name: Get secret zats-democracy-gmail-app-password
  gcp_vault_secret:
    name: "zats-democracy-gmail-app-password"
  register: r_secret_gmail_app_password

- name: Get secret zats-democracy-oauth2-client-id
  gcp_vault_secret:
    name: "zats-democracy-oauth2-client-id"
  register: r_secret_oauth2_client_id

- name: Get secret zats-democracy-oauth2-client-secret
  gcp_vault_secret:
    name: "zats-democracy-oauth2-client-secret"
  register: r_secret_oauth2_client_secret
