---
- name: Get secret zatsit-democracy-{{ env_shortname }}-backup-svcacc-keyfile
  gcp_vault_secret:
    name: "zatsit-democracy-{{ env_shortname }}-backup-svcacc-keyfile"
  register: r_secret_backup_svcacc_keyfile
